CREATE TABLE public.appointments (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    patientname varchar(255) NOT NULL,
    appointmentat timestamptz NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'pending',
    createdat timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT appointments_pkey PRIMARY KEY (id),
    CONSTRAINT appointments_status_check
        CHECK (status IN ('pending', 'confirmed', 'cancelled'))
);